name: Publish Murf MCP

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') && github.event.base_ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install uv
        run: pip install uv

      - name: Verify tag matches version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          FILE_VERSION=$(grep -o "version[ ]*=[ ]*\"[^\"]*\"" pyproject.toml | cut -d'"' -f2)
          echo "Tag: $TAG_VERSION, File: $FILE_VERSION"
          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
            echo "Tag does not match version in pyproject.toml"
            exit 1
          fi

      - name: Build and publish to TestPyPI
        run: |
          uv build
          uv publish --token "${{ secrets.TESTPYPI_TOKEN }}" --publish-url https://test.pypi.org/legacy/
